//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel_Management.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BOOKING
    {
        public int BOOKINGID { get; set; }
        public string BOOKINGSTATUS { get; set; }
        public int USERID { get; set; }
        public int HOTELID { get; set; }
        public System.DateTime BOOKINGDATE { get; set; }
        public int ROOMS { get; set; }
        public Nullable<System.DateTime> BOOKEDFROM { get; set; }
        public Nullable<System.DateTime> BOOKEDTILL { get; set; }
        public int AMOUNT { get; set; }
    
        public virtual HOTEL HOTEL { get; set; }
        public virtual USER USER { get; set; }
    }
}
