//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel_Management.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOTEL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HOTEL()
        {
            this.BOOKINGS = new HashSet<BOOKING>();
        }
    
        public int HOTELID { get; set; }
        public string HOTELNAME { get; set; }
        public string HCITY { get; set; }
        public string HSTATE { get; set; }
        public Nullable<int> TOTALROOMS { get; set; }
        public Nullable<int> BOOKEDROOMS { get; set; }
        public Nullable<float> ROOMPRICE { get; set; }
        public string CONTACTNO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BOOKING> BOOKINGS { get; set; }
    }
}
